// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: index.proto

#ifndef PROTOBUF_index_2eproto__INCLUDED
#define PROTOBUF_index_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_index_2eproto();
void protobuf_AssignDesc_index_2eproto();
void protobuf_ShutdownFile_index_2eproto();

class index_msg_t;

// ===================================================================

class index_msg_t : public ::google::protobuf::Message {
 public:
  index_msg_t();
  virtual ~index_msg_t();
  
  index_msg_t(const index_msg_t& from);
  
  inline index_msg_t& operator=(const index_msg_t& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const index_msg_t& default_instance();
  
  void Swap(index_msg_t* other);
  
  // implements Message ----------------------------------------------
  
  index_msg_t* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const index_msg_t& from);
  void MergeFrom(const index_msg_t& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 magic = 1;
  inline bool has_magic() const;
  inline void clear_magic();
  static const int kMagicFieldNumber = 1;
  inline ::google::protobuf::int32 magic() const;
  inline void set_magic(::google::protobuf::int32 value);
  
  // required int32 flag = 2;
  inline bool has_flag() const;
  inline void clear_flag();
  static const int kFlagFieldNumber = 2;
  inline ::google::protobuf::int32 flag() const;
  inline void set_flag(::google::protobuf::int32 value);
  
  // required int64 key = 3;
  inline bool has_key() const;
  inline void clear_key();
  static const int kKeyFieldNumber = 3;
  inline ::google::protobuf::int64 key() const;
  inline void set_key(::google::protobuf::int64 value);
  
  // required uint64 offset = 4;
  inline bool has_offset() const;
  inline void clear_offset();
  static const int kOffsetFieldNumber = 4;
  inline ::google::protobuf::uint64 offset() const;
  inline void set_offset(::google::protobuf::uint64 value);
  
  // required uint64 size = 5;
  inline bool has_size() const;
  inline void clear_size();
  static const int kSizeFieldNumber = 5;
  inline ::google::protobuf::uint64 size() const;
  inline void set_size(::google::protobuf::uint64 value);
  
  // @@protoc_insertion_point(class_scope:index_msg_t)
 private:
  inline void set_has_magic();
  inline void clear_has_magic();
  inline void set_has_flag();
  inline void clear_has_flag();
  inline void set_has_key();
  inline void clear_has_key();
  inline void set_has_offset();
  inline void clear_has_offset();
  inline void set_has_size();
  inline void clear_has_size();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 magic_;
  ::google::protobuf::int32 flag_;
  ::google::protobuf::int64 key_;
  ::google::protobuf::uint64 offset_;
  ::google::protobuf::uint64 size_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];
  
  friend void  protobuf_AddDesc_index_2eproto();
  friend void protobuf_AssignDesc_index_2eproto();
  friend void protobuf_ShutdownFile_index_2eproto();
  
  void InitAsDefaultInstance();
  static index_msg_t* default_instance_;
};
// ===================================================================


// ===================================================================

// index_msg_t

// required int32 magic = 1;
inline bool index_msg_t::has_magic() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void index_msg_t::set_has_magic() {
  _has_bits_[0] |= 0x00000001u;
}
inline void index_msg_t::clear_has_magic() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void index_msg_t::clear_magic() {
  magic_ = 0;
  clear_has_magic();
}
inline ::google::protobuf::int32 index_msg_t::magic() const {
  return magic_;
}
inline void index_msg_t::set_magic(::google::protobuf::int32 value) {
  set_has_magic();
  magic_ = value;
}

// required int32 flag = 2;
inline bool index_msg_t::has_flag() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void index_msg_t::set_has_flag() {
  _has_bits_[0] |= 0x00000002u;
}
inline void index_msg_t::clear_has_flag() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void index_msg_t::clear_flag() {
  flag_ = 0;
  clear_has_flag();
}
inline ::google::protobuf::int32 index_msg_t::flag() const {
  return flag_;
}
inline void index_msg_t::set_flag(::google::protobuf::int32 value) {
  set_has_flag();
  flag_ = value;
}

// required int64 key = 3;
inline bool index_msg_t::has_key() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void index_msg_t::set_has_key() {
  _has_bits_[0] |= 0x00000004u;
}
inline void index_msg_t::clear_has_key() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void index_msg_t::clear_key() {
  key_ = GOOGLE_LONGLONG(0);
  clear_has_key();
}
inline ::google::protobuf::int64 index_msg_t::key() const {
  return key_;
}
inline void index_msg_t::set_key(::google::protobuf::int64 value) {
  set_has_key();
  key_ = value;
}

// required uint64 offset = 4;
inline bool index_msg_t::has_offset() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void index_msg_t::set_has_offset() {
  _has_bits_[0] |= 0x00000008u;
}
inline void index_msg_t::clear_has_offset() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void index_msg_t::clear_offset() {
  offset_ = GOOGLE_ULONGLONG(0);
  clear_has_offset();
}
inline ::google::protobuf::uint64 index_msg_t::offset() const {
  return offset_;
}
inline void index_msg_t::set_offset(::google::protobuf::uint64 value) {
  set_has_offset();
  offset_ = value;
}

// required uint64 size = 5;
inline bool index_msg_t::has_size() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void index_msg_t::set_has_size() {
  _has_bits_[0] |= 0x00000010u;
}
inline void index_msg_t::clear_has_size() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void index_msg_t::clear_size() {
  size_ = GOOGLE_ULONGLONG(0);
  clear_has_size();
}
inline ::google::protobuf::uint64 index_msg_t::size() const {
  return size_;
}
inline void index_msg_t::set_size(::google::protobuf::uint64 value) {
  set_has_size();
  size_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_index_2eproto__INCLUDED
